INSERT INTO district (number_d, name_d) VALUES
(1, 'Capitole / Arnaud Bernard / Carmes'),
(2, 'Amidonniers / Compans-Caffarelli / Brouardel'),
(3, 'Les Chalets / Bayard / Belfort / Saint-Aubin / Dupuy'),
(4, 'Lapujade / Bonnefoy / Périole / Marengo / La Colonne'),
(5, 'Saint-Michel / Saint-Agne / Empalot / Le Busca / Île du Ramier / Monplaisir'),
(6, 'Saint-Cyprien'),
(7, 'Sept Deniers / Ginestous-Sesquières / Lalande'),
(8, 'Minimes / Barrière de Paris / Ponts-Jumeaux / La Vache / Raisin / Fondeyre'),
(9, 'Trois Cocus / Borderouge / Croix-Daurade / Paleficat / Grand Selve'),
(10, 'Jolimont / Soupetard / Roseraie / Gloire / Gramont / Amouroux'),
(11, 'Bonhoure / Guilheméry / Château de l''Hers / Limayrac / Côte Pavée'),
(12, 'Pont des Demoiselles / Ormeau/ Montaudran / La Terrasse / Malepère'),
(13, 'Rangueil / Sauzelong / Jules-Julien / Pech-David / Pouvourville'),
(14, 'Saint-Simon / Lafourguette / Oncopole - Campus Santé du Futur'),
(15, 'Croix-de-Pierre / Route d''Espagne'),
(16, 'Fontaine-Lestang / Arènes / Bagatelle / Papus / Tabar / Bordelongue / Mermoz / La Faourette'),
(17, 'Mirail -Université / Reynerie / Bellefontaine'),
(18, 'Lardenne / Pradettes / Basso-Cambo'),
(19, 'Casselardit / Fontaine-Bayonne / Cartoucherie'),
(20, 'Arènes Romaines / Ancely / Saint-Martin du Touch / Purpan');